inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Performance/Casecmp:
  Enabled: false

StringLiterals:
  Enabled: false
